// <auto-generated />
using System;
using FantasyStockTracker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FantasyStockTracker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200305041842_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("FantasyStockTracker.Models.Holding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Holdings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a918dd2-3a1c-47e4-a88c-2d2a4710e4ed"),
                            Name = "Value 101"
                        },
                        new
                        {
                            Id = new Guid("96fdccd9-3245-4231-8026-9888bbb11367"),
                            Name = "Value 202"
                        },
                        new
                        {
                            Id = new Guid("16ec86b8-4766-4af0-9d57-dfdf9c9b1d1b"),
                            Name = "Value 303"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
